export const DEPARTMENTS = [
  'Department of Computer Science',
  'Department of Computer Engineering',
  'Department of Architecture',
  'Department of Electrical and Electronic Engineering',
  'Department of Mechanical Engineering',
  'Department of Accounting and Finance',
]

export const PROGRAMMES = ['BSc', 'MSc', 'PhD', 'BEng', 'BTech', 'MBA']

export const LEVELS = ['100', '200', '300', '400', '500', '600']

export const KEYWORDS = ['Blockchain', 'AI', 'Machine Learning', 'Cloud', 'Cybersecurity', 'IoT']

export const PROJECT_TYPES = ['Research Paper', 'Software / App', 'Website', 'Design / Art', 'Other'] as const

// Only actual departments (no colleges/faculties/schools/research centres),
// used as the "Other departments" list where the short DEPARTMENTS
// quick-picks above don't cover a student's actual department.
export const EXTENDED_DEPARTMENTS = [
  'Department of Agricultural Economics, Agribusiness and Extension',
  'Department of Animal Science',
  'Department of Horticulture',
  'Department of Crop and Soil Science',
  'Department of Agroforestry',
  'Department of Fisheries and Watershed Management',
  'Department of Silviculture and Forest Management',
  'Department of Wildlife and Range Management',
  'Department of Wood Science and Technology',
  'Department of Forest Resources Technology',

  'Department of Communication Design',
  'Department of Educational Innovations in Science & Technology',
  'Department of Painting and Sculpture',
  'Department of Indigenous Art and Technology',
  'Department of Industrial Art',
  'Department of Publishing Studies',
  'Department of Construction Technology and Management',
  'Department of Land Economy',
  'Department of Planning',
  'Department of Teacher Education',

  'Department of Commercial Law',
  'Department of Private Law',
  'Department of Public Law',
  'Department of Economics',
  'Department of English',
  'Department of Geography & Rural Development',
  'Department of History & Political Studies',
  'Department of Modern Languages',
  'Department of Sociology & Social Work',
  'Department of Religious Studies',
  'Department of Supply Chain and Information Systems',
  'Department of Human Resource and Organisational Development',
  'Department of Marketing and Corporate Strategy',
  'Department of Hospitality and Tourism Studies',

  'Department of Civil Engineering',
  'Department of Geological Engineering',
  'Department of Geomatic Engineering',
  'Department of Petroleum Engineering',
  'Department of Agricultural and Biosystems Engineering',
  'Department of Chemical Engineering',
  'Department of Material Engineering',
  'Department of Telecommunications Engineering',

  'Department of Nursing',
  'Department of Sports and Exercise Science',
  'Department of Medical Diagnostics',
  'Department of Anaesthesiology & Intensive Care',
  'Department of Anatomy',
  'Department of Behavioural Sciences',
  'Department of Child Health',
  'Department of Clinical Microbiology',
  'Department of Community Health',
  'Department of Eye, Ear, Nose and Throat',
  'Department of Medicine',
  'Department of Molecular Medicine',
  'Department of Obstetrics & Gynaecology',
  'Department of Pathology',
  'Department of Physiology',
  'Department of Radiology',
  'Department of Surgery',
  'Department of Adult Oral Health',
  'Department of Basic Oral Health',
  'Department of Community Dentistry',
  'Department of Oral Health & Orthodontics',
  'Department of Oral & Maxillofacial Science',
  'Department of Herbal Medicine',
  'Department of Pharmaceutics',
  'Department of Pharmacology',
  'Department of Pharmacognosy',
  'Department of Pharmaceutical Chemistry',
  'Department of Pharmacy Practice',
  'Department of Epidemiology & Biostatistics',
  'Department of Global and International Health',
  'Department of Health Policy, Management & Economics',
  'Department of Health Promotion, Education & Disability',
  'Department of Occupational and Environmental Health',
  'Department of Population, Family and Reproductive Health',
  'Department of Veterinary Clinical Studies',
  'Department of Veterinary Anatomy and Physiology',
  'Department of Veterinary Pathobiology',
  'Department of Veterinary Pharmacology and Toxicology',
  'Department of Veterinary Public Health and Epidemiology',

  'Department of Biochemistry and Biotechnology',
  'Department of Environmental Science',
  'Department of Food Science and Technology',
  'Department of Optometry and Visual Science',
  'Department of Theoretical and Applied Biology',
  'Department of Chemistry',
  'Department of Mathematics',
  'Department of Physics',
  'Department of Statistics and Actuarial Science',
  'Department of Meteorology and Climate Science',
]

export const ALL_DEPARTMENTS = Array.from(new Set([...DEPARTMENTS, ...EXTENDED_DEPARTMENTS]))
